package org.broadinstitute.hellbender.tools.walkers.sv;

import com.google.common.annotations.VisibleForTesting;
import htsjdk.samtools.SAMSequenceDictionary;
import htsjdk.samtools.util.IntervalTree;
import htsjdk.variant.variantcontext.VariantContext;
import htsjdk.variant.variantcontext.VariantContextBuilder;
import htsjdk.variant.variantcontext.writer.VariantContextWriter;
import htsjdk.variant.vcf.*;
import org.broadinstitute.barclay.argparser.Argument;
import org.broadinstitute.barclay.argparser.BetaFeature;
import org.broadinstitute.barclay.argparser.CommandLineProgramProperties;
import org.broadinstitute.barclay.help.DocumentedFeature;
import org.broadinstitute.hellbender.cmdline.StandardArgumentDefinitions;
import org.broadinstitute.hellbender.cmdline.programgroups.StructuralVariantDiscoveryProgramGroup;
import org.broadinstitute.hellbender.engine.*;
import org.broadinstitute.hellbender.tools.spark.sv.utils.GATKSVVCFConstants;
import org.broadinstitute.hellbender.tools.sv.SVCallRecord;
import org.broadinstitute.hellbender.tools.sv.SVCallRecordUtils;
import org.broadinstitute.hellbender.utils.*;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Select a subset of records from a structural variant (SV) VCF generated by {@link SVPreprocessRecords}. This tool is distinct from
 * {@link org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants} in that intervals specified with
 * -L and -XL behave differently. Rather than retrieving only records based on their positions as indicated by the
 * index file, all variants are retrieved and then filtered based on the following criteria:
 * <ul>
 *     <li>
 *         minimum overlap fraction with the intervals
 *     </li>
 *     <li>
 *         both endpoints must be contained in the intervals (optional)
 *     </li>
 *     <li>
 *         minimum variant length (all interchromosomal records are retained)
 *     </li>
 * </ul>
 *
 * Output can be restricted to or exclusive of variants only supported by depth-based algorithms ("depth-only").
 *
 * <h3>Inputs</h3>
 *
 * <ul>
 *     <li>
 *         A VCF containing only structural variant records
 *     </li>
 * </ul>
 *
 * <h3>Output</h3>
 *
 * <ul>
 *     <li>
 *         The input VCF with filtered records removed
 *     </li>
 * </ul>
 *
 * <h3>Usage example</h3>
 *
 * <pre>
 *     gatk SVSelectVariants \
 *       -I intervals.intervals_list \
 *       -V variants.vcf.gz \
 *       -O filtered.vcf.gz
 * </pre>
 *
 * @author Mark Walker &lt;markw@broadinstitute.org&gt;
 */

@CommandLineProgramProperties(
        summary = "Annotates structural variants with whether they overlap a given set of intervals",
        oneLineSummary = "Annotates structural variants with whether they overlap a given set of intervals",
        programGroup = StructuralVariantDiscoveryProgramGroup.class
)
@BetaFeature
@DocumentedFeature
public final class SVAnnotateOverlappingRegions extends VariantWalker {
    public static final String REGIONS_NAME_LONG_NAME = "region-name";
    public static final String ADD_REGIONS_LONG_NAME = "add-regions";
    public static final String SUBTRACT_REGIONS_LONG_NAME = "subtract-regions";
    public static final String REGIONS_SET_RULE_LONG_NAME = "region-set-rule";
    public static final String REGIONS_MERGING_RULE_LONG_NAME = "region-merging-rule";
    public static final String REGION_PADDING_LONG_NAME = "region-padding";
    public static final String MIN_OVERLAP_FRACTION_LONG_NAME = "min-overlap-fraction";
    public static final String REQUIRE_BREAKEND_OVERLAP_LONG_NAME = "require-breakend-overlap";

    @Argument(
            doc = "Output VCF",
            fullName = StandardArgumentDefinitions.OUTPUT_LONG_NAME,
            shortName = StandardArgumentDefinitions.OUTPUT_SHORT_NAME
    )
    private GATKPath outputFile;

    @Argument(
            doc = "Region name to use for annotation",
            fullName = REGIONS_NAME_LONG_NAME
    )
    private String regionName;

    @Argument(
            doc = "Interval files to add to annotated regions, can be specified multiple times",
            fullName = ADD_REGIONS_LONG_NAME
    )
    private List<GATKPath> addRegionPaths;

    @Argument(
            doc = "Interval files to subtract from annotated regions, can be specified multiple times",
            fullName = SUBTRACT_REGIONS_LONG_NAME
    )
    private List<GATKPath> subtractRegionPath;

    @Argument(
            doc = "Region interval set rule",
            fullName = REGIONS_SET_RULE_LONG_NAME,
            optional=true
    )
    private IntervalSetRule intervalSetRule = IntervalSetRule.UNION;

    @Argument(
            doc = "Region interval merging rule",
            fullName = REGIONS_MERGING_RULE_LONG_NAME,
            optional=true
    )
    private IntervalMergingRule intervalMergingRule = IntervalMergingRule.OVERLAPPING_ONLY;

    @Argument(
            doc = "Region padding (bp)",
            fullName = REGION_PADDING_LONG_NAME,
            optional=true
    )
    private int regionPadding = 0;

    @Argument(
            doc = "Require at least this overlap fraction with the regions",
            fullName = MIN_OVERLAP_FRACTION_LONG_NAME,
            minValue = 0.,
            maxValue = 1.,
            optional = true
    )
    private double minOverlapFraction = 0.5;

    @Argument(
            doc = "Require both ends of the variant to be included in the regions",
            fullName = REQUIRE_BREAKEND_OVERLAP_LONG_NAME,
            optional = true
    )
    private boolean requireBreakendOverlap = false;

    private SAMSequenceDictionary dictionary;
    private final Map<String,IntervalTree<Object>> includedIntervalsTreeMap = new HashMap<>();
    private VariantContextWriter writer;

    @Override
    public void onTraversalStart() {
        Utils.validateArg(!intervalArgumentCollection.intervalsSpecified(),
                "Arguments -L and -XL are not supported, use --" + ADD_REGIONS_LONG_NAME + " and --" + SUBTRACT_REGIONS_LONG_NAME + " instead");
        dictionary = getHeaderForVariants().getSequenceDictionary();
        Utils.validateArg(dictionary != null, "Sequence dictionary not found in variants header");
        loadIntervalTree();
        writer = createVCFWriter(outputFile);
        writeVCFHeader();
    }

    @Override
    public Object onTraversalSuccess() {
        writer.close();
        return null;
    }

    private void loadIntervalTree() {
        final List<String> addRegionStrings = addRegionPaths.stream().map(GATKPath::toString).collect(Collectors.toList());
        final GenomeLocParser parser = new GenomeLocParser(dictionary);
        final List<SimpleInterval> intervals = IntervalUtils.convertGenomeLocsToSimpleIntervals(IntervalUtils.loadIntervals(addRegionStrings, intervalSetRule, intervalMergingRule, regionPadding, parser).toList());

        for (final SimpleInterval interval : intervals) {
            includedIntervalsTreeMap.putIfAbsent(interval.getContig(), new IntervalTree<>());
            includedIntervalsTreeMap.get(interval.getContig()).put(interval.getStart(), interval.getEnd(), null);
        }
    }

    @Override
    public void apply(VariantContext variant, final ReadsContext readsContext,
                      final ReferenceContext referenceContext, final FeatureContext featureContext) {
        SVCallRecord record = SVCallRecordUtils.create(variant);
        if (intervalIsIncluded(record, includedIntervalsTreeMap)) {
            final VariantContextBuilder builder = new VariantContextBuilder(variant);
            final List<String> regions = new ArrayList<>(variant.getAttributeAsStringList(GATKSVVCFConstants.REGIONS_KEY, null));
            regions.add(regionName);
            builder.attribute(GATKSVVCFConstants.REGIONS_KEY, regions);
            variant = builder.make();
        }
        writer.add(variant);
    }

    private void writeVCFHeader() {
        final VCFHeader inputHeader = getHeaderForVariants();
        final VCFHeader header = new VCFHeader(getDefaultToolVCFHeaderLines(), inputHeader.getSampleNamesInOrder());
        for (final VCFHeaderLine line : inputHeader.getMetaDataInInputOrder()) {
            header.addMetaDataLine(line);
        }
        header.addMetaDataLine(new VCFInfoHeaderLine(GATKSVVCFConstants.REGIONS_KEY, VCFHeaderLineCount.UNBOUNDED, VCFHeaderLineType.String, "List of overlapping regions"));
        writer.writeHeader(header);
    }

    @VisibleForTesting
    protected <T> boolean intervalIsIncluded(final SVCallRecord call, final Map<String, IntervalTree<T>> includedIntervalTreeMap) {
        final IntervalTree<T> startTree = includedIntervalTreeMap.get(call.getContigA());
        // Contig A included
        if (startTree == null) {
            return false;
        }
        final IntervalTree<T> endTree = includedIntervalTreeMap.get(call.getContigB());
        // Contig B included
        if (endTree == null) {
            return false;
        }
        // Breakends both included, if required
        if (requireBreakendOverlap && !(startTree.overlappers(call.getPositionA(), call.getPositionA() + 1).hasNext()
                && endTree.overlappers(call.getPositionB(), call.getPositionB() + 1).hasNext())) {
            return false;
        }
        // Can include all interchromosomal variants at this point
        if (!call.getContigA().equals(call.getContigB())) {
            return true;
        }
        // Check overlap fraction
        final long overlapLength = totalOverlap(call.getPositionA(), call.getPositionB(), startTree);
        final double overlapFraction = overlapLength / (double) (call.getPositionB() - call.getPositionA());
        return overlapFraction >= minOverlapFraction;
    }

    @VisibleForTesting
    protected static <T> long totalOverlap(final int start, final int end, final IntervalTree<T> tree) {
        final Iterator<IntervalTree.Node<T>> iter = tree.overlappers(start, end);
        long overlap = 0;
        while (iter.hasNext()) {
            final IntervalTree.Node<T> node = iter.next();
            overlap += intersectionLength(start, end, node.getStart(), node.getEnd());
        }
        return overlap;
    }

    @VisibleForTesting
    protected static long intersectionLength(final int start1, final int end1, final int start2, final int end2) {
        return Math.max(0, Math.min(end1, end2) - Math.max(start1, start2) + 1);
    }
}
